### ISSUE TITLE
Improve install instructions

### ISSUE THREAD

**Issue by jbboehr** [jbboehr/php-mustache#42]
See: https://github.com/jbboehr/php-handlebars/pull/45#issuecomment-307608879

**Comment by jbboehr** [comment]
* Add instructions for install via PECL
* Change package.xml to indicate the actual minimum required version

**Comment by remicollet** [comment]
Some may prefer binary packages

For Windows => link on pecl
For RPM (Fedora / RHEL / CentOS) => available in my 3rd party repository
=> https://rpms.remirepo.net/

**Comment by renoirb** [comment]
I volunteer to make another Alpine Linux APK release. Please tell me the tag you trust be a good one to be part of Alpine based containers.

**Comment by jbboehr** [comment]
I believe that the installation instruction recommendations have mostly been applied, so I'm going to close this particular issue out.

@renoirb I just tagged 0.9.1 with the latest changes on master (memory leak fix and 7.4 build fixes). Thanks!
