### ISSUE TITLE
crash when HTML is inside tags

### ISSUE THREAD

**Issue by adambaratz** [jbboehr/php-mustache#46]
Received this from a user by email:

> I've been testing the php mustache extension and just encountered a situation where when the extension crashes due to html between the { brackets by mistake, a huge .core dump was saved in the folder every time.

And in a follow up:

> The error was simple - I was replacing str_replace code that used single {}'s for templates and left a piece of old code uncommented so mustache got html inside double {{'s since the inner {} already got replaced where the template had {{{ }}}. But I was a bit concerned because with 500mb .core dumps it would be easy to kill the server space quickly if something like this happened. Basically html inside {{ }} caused the failure.

**Comment by jbboehr** [comment]
I don't suppose he said whether he was using the renderer or the vm.

**Comment by adambaratz** [comment]
No, but my guess is renderer.

**Comment by jbboehr** [comment]
It's actually in the tokenizer.
