### ISSUE TITLE
pecl install error

### ISSUE THREAD

**Issue by ozgurhangisi** [jbboehr/php-mustache#53]
Hi,

I can not install mustache extension on MacOs - php7.3.2. When I try to install mustache with pecl install mustache command I get
the error below. I saw that there is no version 0.8.0 on pecl website.
So I tried pecl mustache-0.8.1 and it says that latest version is 0.8.0.
I tried clear-cache, upgrade but nothing changed. 

pecl install mustache

Could not download from "https://pecl.php.net/get/mustache-0.8.0.tgz",
cannot download "pecl/mustache" (File
https://pecl.php.net:443/get/mustache-0.8.0.tgz not valid (received:
HTTP/1.0 404 Not Found

pecl install mustache-0.8.1

Failed to download pecl/mustache, version "0.8.1", latest release is
version 0.8.0, stability "stable", use
"channel://pecl.php.net/mustache-0.8.0" to install
install failed

**Comment by jbboehr** [comment]
This is rather strange. There must be a desync between the info in the pecl site and whatever interface the command uses. I would recommend installing from source in the meantime. I'll have to either post to the mailing list or perhaps upload a new release to fix the issue.

**Comment by ozgurhangisi** [comment]
Thanks for the response. I install php via brew. So actually I don't know how to do this :( 

I prefer to wait for a new release :)

**Comment by ozgurhangisi** [comment]
Hi,

I Successfully installed mustache 0.9.0 for php 7.3 Now I close the issue

Thanks.
